image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - qa
  - production
  - production-v1

qa:
  stage: qa
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_QA --api-key=$HEROKU_API_KEY
  only:
    - master

production:
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - production

production-v1:
  stage: production-v1
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION_V1 --api-key=$HEROKU_API_KEY_2
  only:
    - 199-integrate-new-map
    
    
